
server:
  port: 9082

jasypt:
  encryptor:
    password: M@x1m0
    algorithm: PBEWithMD5AndTripleDES

amazon:
   access:
     key: ENC(aWNNsaST4Ov+ej7SaGv6Td4OJTATUUa00CYgWYwMAgw=)
     secret-key: ENC(KtBgh/C5pZQCBNwJ2zywsILRB0QqYIr8q7NCRY8Cko5XWflII0iiMCK5P4Ds6GU9BPd8bQKD+/s=)
   region: us-east-1
   end-point:
     url:  https://dynamodb.us-east-1.amazonaws.com

